### PR TITLE
Fix: unable to write across filesystems on Windows

### LINKED ISSUE #22: fcache unable to write across filesystems
fcache uses `os.rename()` to atomically write changes. But, this doesn't work across filesystems.

### LINKED ISSUE #28: OSError: [WinError 17] The system cannot move the file to a different disk drive.
```
  File ... in <module>
    mycache.sync()
  File "c:\Python\x86\38\lib\site-packages\fcache\cache.py", line 183, in sync
    self._write_to_file(filename, self._buffer[ekey])
  File "c:\Python\x86\38\lib\site-packages\fcache\cache.py", line 249, in _write_to_file
    rename(tmp, filename)
  File "c:\Python\x86\38\lib\site-packages\fcache\posixemulation.py", line 95, in rename
    os.rename(src, dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp8nv5st6g' -> 'w:/...\\cache\\74657374'
```

### PR DESCRIPTION
**Pull request by Kronopt**
fix #22 
fix #28

### CODE REVIEW

**Comment by andkirby** [comment]
Hi @Kronopt 

I see, good news — you made the fix! 
Could you please release it?

**Comment by Kronopt** [comment]
I can't merge the pull request, only @tsroten can do it.
But you can clone the repo with my fix, if you want to.

**Comment by andkirby** [comment]
@Kronopt, uh, I see.

> But you can clone the repo with my fix, if you want to.
Yeah, thx for this note.
I just replace the code in a library folder so far.

@tsroten, we're looking forward to getting this fix released. :)

**Comment by yhh2021** [comment]
> @Kronopt, uh, I see.
> 
> > But you can clone the repo with my fix, if you want to.
> 
> Yeah, thx for this note.
> I just replace the code in a library folder so far.
> 
> @tsroten, we're looking forward to getting this fix released. :)

I guess the author has not a Windows environment handy to test.

**Pull request closed without merging**
